FROM openjdk:8-jdk-alpine
RUN apk add --no-cache curl
RUN curl -o /root/job-dsl-core-standalone.jar https://repo.jenkins-ci.org/public/org/jenkins-ci/plugins/job-dsl-core/1.69/job-dsl-core-1.69-standalone.jar
